[versions]
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.1.21"
pebble = "4.1.1"

[libraries]
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
